### ISSUE TITLE
raspberry pi 4 buster

### ISSUE THREAD

**Issue by dazbaker** [philpugh1951/WeatherClock#3]
hey ive been ruining this on raspberry pi 4 buster and it been all ok but ive upgraded to bullseye X64 and on my TFT LCD just shows a blank screen any help on this ?

**Comment by philpugh1951** [comment]
Sorry - been busy - new version runs ok on pi3 with bullseye - but I didn't have to change anything in particular to do this.  Try running it by attaching a keyboard to the Pi 4 and issuing python3 weatherclock.py from the appropriate directory and see what it is complaining about!

**Comment by philpugh1951** [comment]
Unsure of what is going on here - should be no difference between pi4 and pi 3 AFAIK

**Comment by dazbaker** [comment]
ok and i did that and i plug a HDMI in and so it popping up but it in the
sceen on the desktop but it not outputting to the  TFT display ?

**Comment by philpugh1951** [comment]
OK.  This only works if the LCD is the system console - that's all I have tried it on.  I have a Pi3 with the official Pi LCD screen attached.  I don't have a keyboard or mouse attached and I do everything via SSH /WinSCP re-booting the Pi each time.

If your LCD is the default console and you have a keyboard attached, boot the pi, log in and go to the directory where you have  placed weatherclock.py and try to run it from there.  BUT the display has to be the console - not an added peripheral as I haven't been able to get that to work.  It's something about the way pygame handle the display I believe.

Phil

**Comment by dazbaker** [comment]
OK I will try that Phil and if it work is there a hack where I can false it
to boot to the Tft display ?

**Comment by philpugh1951** [comment]
I honestly don't know the answer to that.  That's a question for a Raspberry Pi forum.  There may be a system setting for redirecting the console to a particular device ?

Phil

**Comment by dazbaker** [comment]
OK phill I will take a look there but thank u for updating the script.

**Comment by philpugh1951** [comment]
Quick update.

I 'borrowed' my pi4 from another of my projects.  I couldn't hook it up to the pi LCD screen as it is in a FLIRC heatsink case that doesn't expose the 40 pin header.  I built a clean Bullseye install and copied the weatherclock script to it.  Booting into the console in line mode I could run weatherclock on the HDMI console without any problem - it does look a bit to large on a 50" 4K monitor though (you have to  set the screen size in the script.) !

So if you can connect any graphical display as the console it should work .

Phil

**Comment by dazbaker** [comment]
Hey thank you yes I have done that and yes blank screen on the tft but on
the hdmi lcd it pop up and works fine ?

**Comment by dazbaker** [comment]
I have upgrade to the latest version off cmx and I have noticed that the
figures are not updating but if I manually restart it it starts updating
but then it freezes again any ideas on this issue

**Comment by philpugh1951** [comment]
Hi,

Yes the update was not working correctly – I have modified it yesterday and reloaded – but I am still having issues with timeouts – at least it’s updating again!

Phil

**Comment by dazbaker** [comment]
Ah thank u I will update it and keep an eye on new update before I pester
you lol

**Comment by philpugh1951** [comment]
I have returned WeatherClock to a previous incarnation – There are issues with timeouts if the CumulusMX system is not responding in a timely fashion
But it does update the values now!

Phil

**Comment by dazbaker** [comment]
hey there hope your all well ive just upgrade my pi to the new os x64
but im getting this error


Current thread 0x0000007f9de83040 (most recent call first):
  File "/home/pi/script/./weatherclock.py", line 6 in <module>

any help or dose something need updating?

**Comment by dazbaker** [comment]
and if i plug a hdmi and run with a keyboard im geting this


pygame 1.9.6
Hello from the pygame community. https://www.pygame.org/contribute.html
No protocol specified
No protocol specified
Fatal Python error: PyEval_SaveThread: the function must be called with the
GIL held, but the GIL is released (the current Python thread state is NULL)
Python runtime state: initialized

Current thread 0x0000007f8b874040 (most recent call first):
  File "/home/pi/script/weatherclock.py", line 6 in <module>
Aborted

**Comment by philpugh1951** [comment]
Hi,

Sorry - but GitHub is playing up at present - I can't see your original comments re 64bit OS on Pi.

TBH I haven't tried this and I suspect one of the issues will be the PYGAME module - I don't know if it has been checked as working on the 64bit RPi OS.

At present their web site (pygame.org) is showing as having a problem so it's difficult to check the status.

Phil

**Comment by dazbaker** [comment]
sorry i fogot to put the name off the os


   - System: 64-bit
   - Kernel version: 5.15
   - Debian version: 11 (bullseye)

**Comment by dazbaker** [comment]
hey did u look about the pigamge on the x64

**Comment by dazbaker** [comment]
hey mate sorry to keep going on but it seem that the fist run off the clock
it puts this error

Current thread 0xb6f86980 (most recent call first):
  File "/home/pi/usb-drive/script/weatherclock.py", line 6 in <module>

if i ctrl c and run the command again it seem to work but this not on x64
bit tho

**Comment by dazbaker** [comment]
and soon as i restart it then it dosnt work at all?

**Comment by philpugh1951** [comment]
Sorry for delay.

That line is the first invocation of the pygame module - so the issue would appear to be related to this.

I haven't run this on a pi4 as I only have two of these (running homeassistant and my weather stations/websites) and I don't want to stop any of these to install the 7in Pi display.

It is still running on my Pi 3B under BULLSEYE (32 bit) but that doesn't help you much.  I did try it with other displays (1920*1080) HDMI monitor but with limited success - and this was down to the limitations of the pygame package.  I'm not sure of the status of this package - I used it because i was running the StudioClock (search github for original source) and decided to extend this to include a weather display!  

The existing code expects a 800*400 screen and if different aspect ratio / resolution is required then the whole of the code needs to be modified to account for the change in aspect ratio etc.  It's possible = but I have no need for this as I use the old pi3 and lcd display as an accurate clock and weather console.

Phil

**Comment by dazbaker** [comment]
OK thank you Phil so basically it probably only going to work on the pi 4
on ther older os and not moving forward with the new os so just stay with
the old os is that whatbur saying?

**Comment by dazbaker** [comment]
Just to let you know that ur script is running pretty well on bullseye x64
as I did try it before but still no luck but this time its all working
great  gonna see if it runs in book wrom 2

**Comment by dazbaker** [comment]
Hey there mate I know u don't get involved with ur weather clock anymore

But I'm just wondering as I've got a pi 5 running Bookworm but when I
follow ur instructions on git hub if doesn't run on the screen

Have u got any ideas?

**Comment by philp1951** [comment]
Hi - sorry for lateness!

I haven't tried it with bookworm as yet - I need to set up another pi to do that.  I'll have a look at it sometime but I wonder if it has anything to do with the introduction of WAYLAND as the new display manager?

Phil

**Comment by philp1951** [comment]
Just tried it on my pi 5 / bookworm web host system using a kubuntu 25.04 (WAYLAND) system as the display - it seems to run but I only get the clock and the first column of weather info - I suspect the pygame module is not working correctly yet!

Phil

**Comment by dazbaker** [comment]
Ahh so is there a fix for this?


And I cnt even get it to run on startup using the .bashrc method?

And if I get run the command only nothing open on the little screen?

**Comment by philp1951** [comment]
I have tried it under BOOKWORM and RPi5 and it displays correctly on an X11 display - I haven't tried it with a display yet as I will have to rebuild the system.  

FYI - I have created a new github repository as I had been locked out of this one due to no 2FA in place!  

try downloading from the new repository phil1951

**Comment by dazbaker** [comment]
Ah ok il will try n re download it


And yes if u can rebuild it to work on the 3.5 display that will be great
because I really love thos little clock but now I've upgraded to a pi 5 now
so I would like it on my new pi please


And what start up script shell I use?

**Comment by dazbaker** [comment]
Have u change anything to the code then mate ?

**Comment by philp1951** [comment]
I haven't changed any of the code for a year or so. It is designed to run on the 7inch display as that is the one I have. I don’t know if it would display on a smaller device but the code is not trivial to change as the individual display zones are sized for the Pi display.

**Comment by dazbaker** [comment]
Ok mate but its was running on my pi4 what was running bullseye 64-bit fine

 but as I upgraded to the raspberry Pi 5 running bookworm x64 I can't get
it to display on my 3.5 sceen anymore so something as change in bookworm
and I've used you steps earlier when you got it running on your server

 But still not running on mine ?

Sorry I know it a lote to ask but I really want this on my new set up ?

**Comment by dazbaker** [comment]
Any more update on this mate as I still cnt get this to start on Bookworm
on the Raspberry Pi 5 on the tft screen I've been trying and pulling my
hair out I've searched a hole of the internet chat gbt everything and I'll
just life of   me I just can't get it to work any ideas or have you come to
a stop with this support now?
